name: C/C++ CI

on:
  push:
    branches: [ master, fix/fucking-github ]
  pull_request:
    branches: [ master, fix/fucking-github ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-test
      run: ./ubuntu-build.sh
