name: C/C++ CI

on:
  push:
    branches: [ master, fix/fucking-github ]
  pull_request:
    branches: [ master, fix/fucking-github ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: install dependencies
      run: sudo ./ubuntu-dependencies.sh

    - name: build the project
      run: ./ubuntu-build.sh

    - name: run tests
      run: ./ubuntu-tests.sh
