name: C/C++ CI

on:
  push:
    branches: [ master, CI/add-wiki-generator ]
  pull_request:
    branches: [ master, CI/add-wiki-generator ]

jobs:
  generate_wiki:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: h-shahbazi@hotmail.com
        ACTION_NAME: Hassaniiii
        GH_PAT: 8f4fc12929d24c431826769bae1f1373de40d6e7
        MD_FOLDER: docs/wiki/
        OWNER: Shafty89
        REPO_NAME: Shafty89/0ad
        SKIP_MD: README.md
