name: C/C++ CI

on:
  push:
    branches: [ master, CI/add-wiki-generator ]
  pull_request:
    branches: [ master, CI/add-wiki-generator ]

jobs:
  generate_wiki:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:2.0.1
        env: |
        GH_PAT: 8f4fc12929d24c431826769bae1f1373de40d6e7
        ACTION_MAIL: h-shahbazi@hotmail.com
        ACTION_NAME: Hassaniiii
        OWNER: Shafty89
        REPO_NAME: Shafty89/0ad 
        MD_FOLDER: docs/wiki/
